from tkinter import *
import turtle
from random import uniform

def open_window():
    top = Toplevel()
    top.title("Planete")
    boutonquit = Button(top,text="close",command=top.destroy)
    boutonquit.pack()
    
def systeme():
    
    fond=turtle.Screen()
    fond.bgcolor ( "black" )
    
    font=turtle.Turtle()
    for i in range (100) :    
        font.hideturtle()
        font.penup()
        font.speed(0)
        x=uniform(-600,600)
        y=uniform(-300,300)
        circle_taille= uniform(1,5)
        font.goto(x,y)
        font.pendown()
        font.color('white')
        font.circle(circle_taille)
       
    mer = turtle.Turtle()
    mer.color('orange')
    mer.shape('circle')
    mer.penup()
    mer.setposition(0,-100)
    mer.pendown()
    mer.circle(30)
    ven = turtle.Turtle()
    ven.color('red')
    ven.shape('circle')
    ven.penup()
    ven.setposition(0,-125)
    ven.pendown()
    ven.circle(60)
    ea = turtle.Turtle()
    ea.color('blue')
    ea.shape('circle')
    ea.penup()
    ea.setposition(0,-150)
    ea.pendown()
    ea.circle(100)
    mar = turtle.Turtle()
    mar.color('red')
    mar.shape('circle')
    mar.penup()
    mar.setposition(0,-175)
    mar.pendown()
    mar.circle(130)
    jup = turtle.Turtle()
    jup.color('yellow')
    jup.shape('circle')
    jup.penup()
    jup.setposition(0,-200)
    jup.pendown()
    jup.circle(160)
    sat = turtle.Turtle()
    sat.color('yellow')
    sat.shape('circle')
    sat.penup()
    sat.setposition(0,-225)
    sat.pendown()
    sat.circle(200)
    ur = turtle.Turtle()
    ur.color('cyan')
    ur.shape('circle')
    ur.penup()
    ur.setposition(0,-275)
    ur.pendown()
    ur.circle(260)
    nep = turtle.Turtle()
    nep.color('blue')
    nep.shape('circle')
    nep.penup()
    nep.setposition(0,-300)
    nep.pendown()
    nep.circle(300)
    for i in range (100):
        mer.circle(30)
        ven.circle(60)
        ea.circle(100)
        mar.circle(130)
        jup.circle(160)
        sat.circle(200)
        ur.circle(260)
        nep.circle(300)


root = Tk()
canvas = Canvas(master = root, width = 500, height = 500)
canvas.pack()
bouton = Button(root,text="Start", command=systeme)
bouton.pack()

bouton_mer = Button(root, text="open window", command=open_window)
bouton_mer.pack(side=LEFT)
bouton_ven = Button(root, text="open window", command=open_window)
bouton_ven.pack(side=LEFT)
bouton_ter = Button(root, text="open window", command=open_window)
bouton_ter.pack(side=LEFT)
bouton_mar = Button(root, text="open window", command=open_window)
bouton_mar.pack(side=LEFT)
bouton_jup = Button(root, text="open window", command=open_window)
bouton_jup.pack(side=LEFT)
bouton_sat = Button(root, text="open window", command=open_window)
bouton_sat.pack(side=LEFT)
bouton_ur = Button(root, text="open window", command=open_window)
bouton_ur.pack(side=LEFT)
bouton_nep = Button(root, text="open window", command=open_window)
bouton_nep.pack(side=LEFT)

root.mainloop()


print ("juste le code du systeme")

import turtle
from random import uniform
fond=turtle.Screen()

fond.bgcolor ( "black" )
font=turtle.Turtle()
for i in range (100) :
       font.hideturtle()
       font.penup()
       font.speed(0)
       x=uniform(-500,500)
       y=uniform(-300,300)
       circle_taille= uniform(1,5)
       font.goto(x,y)
       font.pendown()
       font.color('white')
       font.circle(circle_taille)

       
mer = turtle.Turtle()
mer.color('orange')
mer.shape('circle')
mer.penup()
mer.setposition(0,-100)
mer.pendown()
mer.circle(30)

ven = turtle.Turtle()
ven.color('red')
ven.shape('circle')
ven.penup()
ven.setposition(0,-125)
ven.pendown()
ven.circle(60)

ea = turtle.Turtle()
ea.color('blue')
ea.shape('circle')
ea.penup()
ea.setposition(0,-150)
ea.pendown()
ea.circle(100)

mar = turtle.Turtle()
mar.color('red')
mar.shape('circle')
mar.penup()
mar.setposition(0,-175)
mar.pendown()
mar.circle(130)

jup = turtle.Turtle()
jup.color('yellow')
jup.shape('circle')
jup.penup()
jup.setposition(0,-200)
jup.pendown()
jup.circle(160)

sat = turtle.Turtle()
sat.color('yellow')
sat.shape('circle')
sat.penup()
sat.setposition(0,-225)
sat.pendown()
sat.circle(200)

ur = turtle.Turtle()
ur.color('cyan')
ur.shape('circle')
ur.penup()
ur.setposition(0,-275)
ur.pendown()
ur.circle(260)

nep = turtle.Turtle()
nep.color('blue')
nep.shape('circle')
nep.penup()
nep.setposition(0,-300)
nep.pendown()
nep.circle(300)

for i in range (100):
    mer.circle(30)
    ven.circle(60)
    ea.circle(100)
    mar.circle(130)
    jup.circle(160)
    sat.circle(200)
    ur.circle(260)
    nep.circle(300)
